if(void 0==otm)var otm={};otm.url={rpc:"/rpc.php",view:{trails:"/trail/envelope",trail:"/trail/?id=",training:"/viewtraining/?id=",poi:"/poi/"}};otm.color={trail:"#ff0000",grade:["#FFFFFF","#00FF00","#0000FF","#FF0000","#000000"]};
otm.icons={base:"/img/map/",grade:["/img/map/cyclingmountainnotrated.png","/img/map/cyclingmountain1.png","/img/map/cyclingmountain2.png","/img/map/cyclingmountain3.png","/img/map/cyclingmountain4.png"],numeric:"/img/map/km/red",finish:"/img/map/finish.png",high:"/img/map/up.png",low:"/img/map/down.png",trail:"/img/map/smallRoundRed.png",poi:{landmark:"/img/map/smallRoundRed.png"},getNumeric:function(a){return otm.icons.numeric+a+".png"}};void 0==otm&&(otm={});otm.trail=null;otm.trails=null;
otm.map={trail:[],trails:[],markers:[],instance:null,geocoder:null,options:{zoom:2,center:null,mapTypeId:null},init:function(a){google||alert("Google maps not loaded");otm.map.options.center=new google.maps.LatLng(0,0);otm.map.options.mapTypeId=google.maps.MapTypeId.ROADMAP;var b=window.location.hash.substr(1).parseQueryString();b.lat&&b.lng&&b.zoom?(otm.map.options.center=new google.maps.LatLng(b.lat,b.lng),otm.map.options.zoom=parseInt(b.zoom)):(otm.map.options.center=a&&a.lat&&a.lng?new GLatLng(a.lat,
a.lng):otm.map.geoLocation(),otm.map.options.zoom=12);otm.map.options.mapTypeControlOptions={mapTypeIds:["OSM",google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.HYBRID,google.maps.MapTypeId.SATELLITE,google.maps.MapTypeId.TERRAIN]};otm.map.geocoder=new google.maps.Geocoder;otm.map.osmMapType=new google.maps.ImageMapType({getTileUrl:function(a,b){return"http://tile.openstreetmap.org/"+b+"/"+a.x+"/"+a.y+".png"},tileSize:new google.maps.Size(256,256),isPng:!0,alt:"Visa OpenStreetMap karta",name:"OSM",
maxZoom:19});otm.map.instance=new google.maps.Map(document.getElementById("map_canvas"),otm.map.options);otm.map.instance.mapTypes.set("OSM",otm.map.osmMapType);return otm.map.instance},geoLocation:function(a){var b;b=google.loader&&google.loader.ClientLocation?new google.maps.LatLng(google.loader.ClientLocation.latitude,google.loader.ClientLocation.longitude):new google.maps.LatLng(59.2833,18.05);if(a)otm.map.instance.setCenter(b,12);else return b},osmMapType:null,showAddress:function(a){if(!otm.map.geocoder)return!1;
-1==a.indexOf(",")&&google.loaderClientLocation&&(a=a+", "+google.loader.ClientLocation.address.country);otm.map.geocoder.geocode({address:a},function(b,c){c!=google.maps.GeocoderStatus.OK?alert(a+" not found"):otm.map.instance.setCenter(b[0].geometry.location,11)})},search:{init:function(){var a=$("mapLocationSearch");a&&a.addEvent("submit",function(a){a.preventDefault();otm.map.showAddress(this.address.value);return!1})}}};
otm.drawTrail=function(a,b){b||(b={});for(var c=a.length,d=[],e=0;e<c;e++)d.push(new google.maps.LatLng(a[e].lat,a[e].lng));return new google.maps.Polyline({path:d,strokeColor:b.color?b.color:otm.color.trail,strokeOpacity:b.opacity?b.opacity:0.5,strokeWeight:b.weight?b.weight:2,zIndex:b.zIndex?b.zIndex:null,map:b.map?b.map:otm.map.instance})};
otm.onDrawTrail=function(a){google.maps.event.addListener(a,"mouseover",function(){window.cursor="point";$("name").set("text",this.name);$("name").set("href",otm.url.view.trail+this.trailId);$("name").addEvent("click",otm.setHistory);$("length").set("text",this.length+"km");$("grade").set("text",this.grade)});var b=new Element("li",{id:a.trailId,events:{mouseover:function(){var a=otm.trails.getTrail(this.get("id"));a.origColor=a.strokeColor;a.setOptions({strokeColor:"#9400d3"});$("name").set("text",
a.name);$("name").set("href",otm.url.view.trail+a.trailId);$("name").addEvent("click",otm.setHistory);$("length").set("text",a.length+"km");$("grade").set("text",a.grade)},mouseout:function(){var a=otm.trails.getTrail(this.get("id"));a.setOptions({strokeColor:a.origColor})}}}),c=$("result");c.retrieve("empty",!0)&&(c.empty(),c.store("empty",!1));var d=new Element("div"),e=new Element("a",{href:otm.url.view.trail+a.trailId,events:{click:otm.setHistory},text:a.name});d.grab(e);b.grab(d);c.grab(b);c.getFirst().getFirst().hasClass("top")||
c.getFirst().getFirst().addClass("top");otm.onTrailClick(a)};otm.onTrailClick=function(a){google.maps.event.addListener(a,"click",function(){otm.setHistory();if(this.poi)window.location=viewpoi+this.poi;else if(this.trail)window.location=otm.url.view.trail+this.trailId})};otm.onUnlinkTrail=function(a){var b=$(a.trailId);b.getFirst().hasClass("top")&&b.getNext()&&b.getNext().getFirst().addClass("top");$(a.trailId).destroy()};
otm.onDrawMarker=function(a){google.maps.event.addListener(a,"mouseover",function(){var a=$("result");a.empty();var c=new Element("ul",{"class":"sidelist"}),d=function(d){var e=new Element("li"),d=new Element("div",{html:d});0<a.getChildren().length&&!a.contains("firstResult")&&(e.set("id","firstResult"),d.set("class","top"));d.inject(e);e.inject(c)};d("Namn: "+this.name);d("Längd: "+this.length+"km");var e="";switch(this.grade){case "1":e="grön";break;case "2":e="blå";break;case "3":e="röd";break;
case "4":e="svart";break;default:e=this.grade}d("Grad: "+e);$("result").grab(c)});otm.onTrailClick(a)};void 0==otm&&(otm={});otm.setHistory=function(){window.location.hash="lat="+otm.map.instance.getCenter().lat()+"&lng="+otm.map.instance.getCenter().lng()+"&zoom="+otm.map.instance.getZoom()};
otm.distance=function(a,b){var c=function(a){return a*Math.PI/180},d=c(b.lat()-a.lat()),e=c(b.lng()-a.lng()),c=Math.sin(d/2)*Math.sin(d/2)+Math.cos(c(a.lat()))*Math.cos(c(b.lat()))*Math.sin(e/2)*Math.sin(e/2);return(6367445*2*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))).toFixed(3)};
otm.challange=function(){var a=otm.map.init();otm.map.instance=a;a=new Trail(13,a,{events:{click:function(a){new Gate(otm.map.instance,a.latLng,otm.trail.polyline,{autoTune:!0})}}});otm.trail=a;$("autoAdd").addEvent("click",function(a){a.preventDefault();this.dist=this.gates=0;a=otm.trail.polyline.getPath();a.forEach(function(a,b){0!=b&&(this.dist+=Number(otm.distance(this.prev,a)),this.dist>1E3*this.gates&&(new Gate(otm.map.instance,a,otm.trail.polyline,{autoTune:!0,distance:50}),this.gates+=1));
this.prev=a}.bind(this));new Gate(otm.map.instance,a.getAt(a.getLength()-2),otm.trail.polyline,{autoTune:!0,distance:50});a.getLength()}.bind(this));$("startGate").addEvent("click",function(a){a.preventDefault();new Gate(otm.map.instance,otm.trail.polyline.getPath().getAt(0),otm.trail.polyline)}.bind(this));$("addGate").addEvent("click",function(a){a.preventDefault();google.maps.event.addListenerOnce(otm.map.instance,"click",function(a){new Gate(otm.map.instance,a.latLng,otm.trail.polyline)})})};
otm.refresh=function(){var a=window.getSize().y-45;$("map_canvas").setStyle("height",a);$$(".auto-size-v").setStyle("height",a);$$(".auto-size-bv").each(function(b){var c=b.getComputedSize(),d=c.totalHeight+(""==b.getStyle("margin-top")?0:parseInt(b.getStyle("margin-top")))+(""==b.getStyle("margin-botom")?0:parseInt(b.getStyle("margin-botom")));b.setStyle("height",a-(d-c.height))});$("ds-v").getChildren().setStyle("height",a);otm.map.instance&&google.maps.event.trigger(otm.map.instance,"resize")};
otm.viewTrailsFluid=function(){var a=window.location.search.substr(1).parseQueryString(),b;otm.refresh();window.addEvent("resize",function(){$clear(b);b=otm.refresh.delay(50)});$$(".trail-info-short").addEvent("click",function(){$("trail-info").removeClass("hide");var a=new Fx.Tween("trails-info",{transition:"quad:out",duration:1E3,property:"right"}),b=new Fx.Tween("trail-info",{transition:"quad:out",duration:1E3,property:"right"});a.start(0,-350);b.start(350,0)});$$(".panel-arrow").addEvent("click",
function(){var a=new Fx.Tween(this.getParent(".sidebar"),{transition:"linear",duration:500,property:"right"}),b=new Fx.Tween("map",{transition:"linear",duration:500,property:"margin-right"});a.start(-350);b.start(0).chain(function(){google.maps.event.trigger(otm.map.instance,"resize");new MapControl(otm.map.instance,{controls:["showPanel"],restore:{action:function(){window.location=otm.url.view.trails}}})})});a.fullscreen&&1==a.fullscreen&&$("map_canvas").setStyle("height",window.innerHeight-70);
a=otm.map.init();otm.trails=new Trails(a,void 0);otm.pois=new Pois(a,{maxZoom:1})};
otm.viewTrails=function(){var a=window.location.search.substr(1).parseQueryString();a.fullscreen&&1==a.fullscreen&&$("map_canvas").setStyle("height",window.innerHeight-70);var b=otm.map.init();a.fullscreen&&1==a.fullscreen?(new MapControl(b,{controls:["restore"],restore:{action:function(){window.location=otm.url.view.trails}}}),a={onDrawTrail:otm.onTrailClick}):(new MapControl(b,{controls:["maximize"],maximize:{action:function(){window.location=otm.url.view.trails+"?fullscreen=1"}}}),a={onDrawTrail:otm.onDrawTrail,
onUnlinkTrail:otm.onUnlinkTrail,onDrawTrailMarker:otm.onDrawMarker});otm.map.search.init();a.markers=!0;otm.trails=new Trails(b,a);otm.pois=new Pois(b,{maxZoom:1})};
otm.viewTrail=function(){var a=window.location.search.substr(1).parseQueryString(),b=a.id?a.id:-1,c=otm.map.init();new Trail(b,c);a.fullscreen&&1==a.fullscreen?($("map_canvas").setStyle("height",window.innerHeight-70),new MapControl(c,{controls:["allTrails","restore"],restore:{id:b,action:function(){window.location=otm.url.view.trail+b}},allTrails:{id:b}})):(new MapControl(c,{controls:["maximize"],maximize:{id:b,action:function(){window.location=otm.url.view.trail+b+"&fullscreen=1"}}}),new Likes("star",
b),(new Request.JSON({url:otm.url.rpc,onSuccess:function(a){if(a.error)return console&&console.log&&console.log(a.error),!1;new Chart("contourLine",{series:[{name:"Höjd över havet (m)",color:"#177245",data:a.data}]})},data:{call:"trail.get.elevation",id:b}})).get())};
otm.viewTraining=function(){var a=window.location.search.substr(1).parseQueryString(),b=a.id?a.id:-1,c=otm.map.init();otm.trail=new Trail(b,c,{call:"training.get.polyline"});a.fullscreen&&1==a.fullscreen?($("map_canvas").setStyle("height",window.innerHeight-70),new MapControl(c,{controls:["allTrails","restore"],restore:{id:b,action:function(){window.location=otm.url.view.training+b}},allTrails:{id:b}})):(new MapControl(c,{controls:["maximize"],maximize:{id:b,action:function(){window.location=otm.url.view.training+
b+"&fullscreen=1"}}}),otm.viewControl(),(new Request.JSON({url:otm.url.rpc,onSuccess:function(a){var b=$("graphs");if(a.datasets.altitude){new Element("div");var c=[{name:"Höjd över havet (m)",shortname:"m ö.h.",color:"#177245",data:a.datasets.altitude.data}];a.datasets.heartrate&&c.push({name:"Puls (slag/min)",shortname:"Puls",color:"#fc6355",type:"line",yAxis:1,data:a.datasets.heartrate.data});new Chart(b,{series:c})}},data:{call:"training.get.graphs",id:b}})).get())};
otm.workoutTable=function(){document.id("workouts").getElement("tbody").getElements("tr").each(function(a){a.addEvent("click",function(){window.location=otm.url.view.training+a.get("id").slice(2)});a.getElements("td.delete").addEvent("click",function(b){b.preventDefault();(new Event(b)).stop();confirm("Vill du verkligen tabort träningsrundan?")&&(new Request.JSON({url:otm.url.rpc,onSuccess:function(b){1==b.code?a.dispose():alert("Det gick inte att ta bort träningsrundan")},data:{call:"training.delete",
id:a.get("id").slice(2)}})).get()})})};
otm.viewControl=function(){if(!$("viewcontrol"))return!1;new ContextMenu({targets:"#viewcontrol",menu:"contextmenu",trigger:"click",targetParent:!0,actions:{startend:function(a){otm.trail.toggleStartIcon();otm.trail.toggleEndIcon();a.toggleClass("enabled");a.hasClass("enabled")?a.set("text","dölj start/slut"):a.set("text","visa start/slut")},kmMarkers:function(a){otm.trail.toggleKmIcons();a.toggleClass("enabled");a.hasClass("enabled")?a.set("text","dölj km markeringar"):a.set("text","visa km markeringar")},
highest:function(a){otm.trail.toggleHighOverlay();a.toggleClass("enabled");a.hasClass("enabled")?a.set("text","dölj högsta punkt"):a.set("text","visa högsta punkt")},lowest:function(a){otm.trail.toggleLowOverlay();a.toggleClass("enabled");a.hasClass("enabled")?a.set("text","dölj lägsta punkt"):a.set("text","visa lägsta punkt")},contour:function(a){otm.trail.toggleElevationOverlay();a.toggleClass("enabled");a.hasClass("enabled")?a.set("text","dölj höjdkurva"):a.set("text","visa höjdkurva")},center:function(){otm.trail.center()}},
offsets:{x:-145,y:11}})};
otm.viewPoi=function(){var a=0,b=window.location.search.substr(1).parseQueryString();if(b.id)a=b.id;otm.map.init();(new Request.JSON({url:otm.url.rpc,onSuccess:function(a){1==a.code?(poi=new google.maps.Marker({position:new google.maps.LatLng(a.lat,a.lng),icon:otm.icons.poi.landmark,map:otm.map.instance}),otm.map.instance.setCenter(poi.getPosition()),$("centerControl").addEvent("click",function(a){a.preventDefault();otm.map.instance.panTo(poi.getPosition())})):console.log("callback error: "+a.error)}})).get({call:"getPoi",
id:a});SqueezeBox.initialize({handler:"image",overlayOpacity:0.2});SqueezeBox.assign($$(".thumbnail"))};
var Chart=new Class({Implements:[Options,Events],options:{series:null,title:null,id:null,y:{title:"",unit:""}},target:null,chart:null,initialize:function(a,b){this.setOptions(b);this.target=a;!this.options.series&&this.options.call&&this.options.id?this.request():this.options.series&&this.createChart(this.options.series)},request:function(){(new Request.JSON({url:otm.url.rpc,onSuccess:this.requestCallback.bind(this),data:{call:this.options.call,id:this.options.id}})).get()},requestCallback:function(a){0==
a.status?alert("unable to load graph data: "+a.errorMessage):a.data&&this.createChart(a.data)},createChart:function(a){var b=[{labels:{formatter:function(){return this.value+(a[0].unit?a[0].unit:"")}},title:{enabled:!0,text:a[0].name?a[0].name:"",margin:35}},{labels:{formatter:function(){return this.value+(a[1]&&a[1].unit?a[1].unit:"")}},opposite:!0,title:{enabled:!0,text:a[1]&&a[1].name?a[1].name:"",margin:40}}];this.chart=new Highcharts.Chart({chart:{renderTo:this.target,defaultSeriesType:"area",
width:document.getElementById("map_canvas").get("width"),height:250,margin:[10,55,60,50]},credits:{enabled:!1},title:{text:this.options.title},yAxis:b,xAxis:{labels:{formatter:function(){return this.value/1E3}}},plotOptions:{area:{animation:!1,allowPointSelect:!1,threshold:-1E5,marker:{enabled:!1,symbol:"circle",radius:2,states:{hover:{enabled:!1}}}},line:{animation:!1,lineWidth:1,allowPointSelect:!1,marker:{enabled:!1,symbol:"circle",radius:2,states:{hover:{enabled:!1}}},states:{hover:{lineWidth:1}}}},
tooltip:{enabled:!1},legend:{enabled:!0},series:a})}}),Trail=new Class({Implements:[Options,Events],options:{colorGraded:!1,color:otm.color.trail,polyline:!0,opacity:0.5,weight:2,center:!0,call:"trail.get.polyline",overlay:{start:!1,end:!1,km:!1,highest:!1,lowest:!1},events:{click:null}},map:null,id:null,bounds:null,start:null,end:null,km:[],highest:null,polyline:null,elePolylines:null,isRedrawing:!1,initialize:function(a,b,c){this.setOptions(c);this.map=b;this.id=a;this.bounds=new google.maps.LatLngBounds;
this.setupControls();this.request()},redraw:function(){this.remove();this.request()},request:function(){(new Request.JSON({url:otm.url.rpc,onSuccess:this.draw.bind(this),data:{call:this.options.call,id:this.id}})).get()},setupControls:function(){var a=document.getElementById("centerControl");a&&a.addEvent("click",function(a){a.preventDefault();this.center()}.bind(this));var b=document.getElementById("startControl");b&&b.addEvent("click",function(a){a.preventDefault();b.hasClass("active")?b.set("text",
"visa start/slut"):b.set("text","dölj start/slut");b.toggleClass("active");this.toggleEndIcon();this.toggleStartIcon()}.bind(this));var c=document.getElementById("kmControl");c&&c.addEvent("click",function(a){a.preventDefault();c.hasClass("active")?c.set("text","visa km markeringar"):c.set("text","dölj km markeringar");c.toggleClass("active");this.toggleKmIcons()}.bind(this));var d=document.getElementById("contourTrailControl");d&&d.addEvent("click",function(a){a.preventDefault();d.hasClass("active")?
d.set("text","visa höjdkurva"):d.set("text","dölj höjdkurva");d.toggleClass("active");this.toggleElevationOverlay()}.bind(this));var e=document.getElementById("highControl");e&&e.addEvent("click",function(a){a.preventDefault();e.hasClass("active")?e.set("text","visa högsta punkt"):e.set("text","dölj högsta punkt");e.toggleClass("active");this.toggleHighOverlay()}.bind(this));var f=document.getElementById("lowControl");f&&f.addEvent("click",function(a){a.preventDefault();f.hasClass("active")?f.set("text",
"visa lägsta punkt"):f.set("text","dölj lägsta punkt");f.toggleClass("active");this.toggleLowOverlay()}.bind(this))},toggleStartIcon:function(){if(!this.start)this.start=new google.maps.Marker({position:new google.maps.LatLng(this.polyline.points.start.lat,this.polyline.points.start.lng),icon:this.polyline.grade?otm.icons.grade[this.polyline.grade]:otm.icons.grade[0]});this.start.map?this.start.setMap(null):this.start.setMap(this.map)},toggleEndIcon:function(){if(!this.end)this.end=new google.maps.Marker({position:new google.maps.LatLng(this.polyline.points.end.lat,
this.polyline.points.end.lng),icon:otm.icons.finish});this.end.map?this.end.setMap(null):this.end.setMap(this.map)},toggleKmIcons:function(){0==this.km.length&&this.polyline.points.km.each(function(a,b){this.km.push(new google.maps.Marker({position:new google.maps.LatLng(a.lat,a.lng),icon:otm.icons.getNumeric(b+1)}))}.bind(this));this.km.each(function(a){a.map?a.setMap(null):a.setMap(this.map)}.bind(this))},toggleHighOverlay:function(){if(!this.high)this.high=new google.maps.Marker({position:new google.maps.LatLng(this.polyline.points.highest.lat,
this.polyline.points.highest.lng),icon:otm.icons.high});this.high.map?this.high.setMap(null):this.high.setMap(this.map)},toggleLowOverlay:function(){if(!this.low)this.low=new google.maps.Marker({position:new google.maps.LatLng(this.polyline.points.lowest.lat,this.polyline.points.lowest.lng),icon:otm.icons.low});this.low.map?this.low.setMap(null):this.low.setMap(this.map)},toggleElevationOverlay:function(){this.polyline.map?(this.polyline.setMap(null),this.elePolylines?this.elePolylines.each(function(a){a.setMap(this.map)}.bind(this)):
(new Request.JSON({url:otm.url.rpc,onSuccess:this.loadElevationOverlay.bind(this),data:{call:this.options.call+".elevation",id:this.polyline.trailId}})).get()):(this.elePolylines.each(function(a){a.setMap(null)}),this.polyline.setMap(this.map))},loadElevationOverlay:function(a){0==a.code&&alert("Unable to load color coded map trail");if(!this.elePolylines)this.elePolylines=[];a.trail.each(function(a){var c=[];a.points.each(function(a){c.push(new google.maps.LatLng(a.lat,a.lng))});this.elePolylines.push(new google.maps.Polyline({path:c,
strokeColor:a.color,strokeOpacity:this.options.opacity,strokeWeight:this.options.weight,map:this.map}))}.bind(this))},center:function(){this.map.fitBounds(this.bounds)},draw:function(a){if(0!=a.code){if(this.polyline)this.polyline.setMap(null),this.polyline=null;if(this.options.colorGraded&&a.grade)this.options.color=otm.color.grade[a.grade];for(var b=a.trail,c=b.length,d=[],e=0;e<c;e++){var f=new google.maps.LatLng(b[e].lat,b[e].lng);d.push(f);this.bounds.extend(f)}b=new google.maps.Polyline({path:d,
strokeColor:this.options.color,strokeOpacity:this.options.opacity,strokeWeight:this.options.weight,map:this.map});this.options.events.click&&google.maps.event.addListener(b,"click",this.options.events.click);this.options.center&&this.center();b.trailId=a.id;b.name=a.name;b.grade=a.grade;b.length=a.distance;b.points=a.points;this.polyline=b}},remove:function(){if(this.polyline)this.fireEvent("onUnlinkTrail",[this.polyline]),this.polyline.setMap(null),this.polyline=null}}),Line=new Class({Implements:[Options],
Binds:["intersect"],options:{display:!0},p1:null,p2:null,polyline:null,map:null,initialize:function(a,b,c){this.map=c.map?c.map:null;c.map=null;this.setOptions(c);this.p1=a;this.p2=b;if(this.map)this.polyline=new google.maps.Polyline({map:this.map,path:[a,b]});this._calculate()},update:function(a,b){this.p1=a;this.p2=b;this.polyline.getPath().setAt(0,this.p1);this.polyline.getPath().setAt(1,this.p2);this._calculate()},_calculateDDD:function(){this.dx=this.p1.lng()-this.p2.lng();this.dy=this.p1.lat()-
this.p2.lat()},_calculate:function(){this.xm=this.p1.lat()/2+this.p2.lat()/2;this.ym=(this.p1.lng()+this.p2.lng())/2;this.a=this.p2.lat()-this.p1.lat();this.b=this.p1.lng()-this.p2.lng();this.c=this.a*(this.p1.lng()-this.xm)+this.b*(this.p1.lat()-this.ym)},_intersect:function(a,b){var c=this.a*(a.p1.lng()-this.xm)+this.b*(a.p1.lat()-this.ym)-this.c,d=this.a*(a.p2.lng()-this.xm)+this.b*(a.p2.lat()-this.ym)-this.c;return 0==c||0==d?!0:0<c&&0>d||0>c&&0<d?b?!0:(new Line(a.p1,a.p2))._intersect(this,!0):
!1},intersect:function(a){var a=a.getPath(),b;try{a.forEach(function(a,c){if(0!=c&&this._intersect({p1:b,p2:a}))throw"intersect";b=a}.bind(this))}catch(c){if("intersect"==c)return!0}return!1}}),Gate=new Class({Implements:[Options,Events],options:{trail:null,autoTune:!1,distance:12,heading:90,author:"nils",events:{rightclick:Function.from(!0)}},map:null,marker1:null,marker2:null,polyline:null,line:null,initialize:function(a,b,c,d){this.setOptions(d);this.map=a;this.trail=c;if(this.options.autoTune){var e=
99999999,f=-1,g=null,a=this.trail.getPath();a.forEach(function(a,c){var d=google.maps.geometry.spherical.computeDistanceBetween(b,a);e>d&&(e=d,f=c,g=a)});this.options.heading=google.maps.geometry.spherical.computeHeading(a.getAt(f-1),a.getAt(f+1));b=g}this.marker1=new google.maps.Marker({map:this.map,position:new google.maps.geometry.spherical.computeOffset(b,this.options.distance,this.options.heading-90),draggable:!0,raiseOnDrag:!1,flat:!0,title:"Drag me!"});this.marker2=new google.maps.Marker({map:this.map,
position:new google.maps.geometry.spherical.computeOffset(b,this.options.distance,this.options.heading+90),raiseOnDrag:!1,flat:!0,draggable:!0,title:"Drag me!"});this.line=new Line(this.marker1.getPosition(),this.marker2.getPosition(),{map:this.map});Event.Keys.shift=16;(new Keyboard({events:{"keydown:shift":function(){this.shift=!0}.bind(this),"keyup:shift":function(){this.shift=!0}.bind(this)}})).activate();window.addEvent("keydown",function(a){if("shift"==a.key)this.shift=!0}.bind(this));window.addEvent("keyup",
function(a){if("shift"==a.key)this.shift=!1}.bind(this));google.maps.event.addListener(this.marker1,"drag",this.marker1moved.bind(this));google.maps.event.addListener(this.marker1,"rightclick",this.showContextMenu.bind(this));google.maps.event.addListener(this.marker2,"drag",this.marker2moved.bind(this));google.maps.event.addListener(this.marker2,"rightclick",this.showContextMenu.bind(this))},toArray:function(){return[{lat:this.marker1.getPosition().lat(),lng:this.marker1.getPosition().lng()},{lat:this.marker2.getPosition().lat(),
lng:this.marker2.getPosition().lng()}]},showContextMenu:function(a){var b=$("contextmenu");b&&b.dispose();var c=Element("ul",{id:"contextmenu"});[{label:"Delete",event:function(){this.marker1.setMap(null);this.marker2.setMap(null);this.line.polyline.setMap(null);delete this.marker1;delete this.marker2;delete this.line;this.fireEvent("delete",this);$("contextmenu").dispose()}}].each(function(a){var b=new Element("li");b.grab(new Element("a",{id:a.id?a.id:null,text:a.label,styles:{cursor:"default",
"border-top":a.separator?"1px solid #999":null,"border-bottom":a.bottomSeparator?"1px solid #999":null},events:{click:a.event.bind(this)}}));c.grab(b)}.bind(this));$(prune.map.getDiv()).grab(c);var b=$("map_canvas").getSize(),d=c.getSize(),a=a.pixel;a.y-=15;if(b.x-a.x<d.x)a.x=b.x-d.x;b.y-a.y<d.y&&(a.y-=d.y);c.setStyles({left:a.x,top:a.y,visibility:"visible",display:"block"})},marker1moved:function(){if(this.shift){var a=this.line.polyline.getPath().getAt(0),b=this.marker1.getPosition(),c=b.lat()-
a.lat(),a=b.lng()-a.lng(),b=this.marker2.getPosition();this.marker2.setPosition(new google.maps.LatLng(b.lat()+c,b.lng()+a))}this.redraw()},marker2moved:function(){if(this.shift){var a=this.line.polyline.getPath().getAt(1),b=this.marker2.getPosition(),c=b.lat()-a.lat(),a=b.lng()-a.lng(),b=this.marker1.getPosition();this.marker1.setPosition(new google.maps.LatLng(b.lat()+c,b.lng()+a))}this.redraw()},redraw:function(){this.line.update(this.marker1.getPosition(),this.marker2.getPosition());this.check()},
check:function(){return this.line.intersect(this.trail)}}),SimpleModal=new Class({Implements:[Options],request:null,buttons:[],options:{onAppend:Function,offsetTop:null,overlayOpacity:0.3,overlayColor:"#000000",width:400,draggable:!0,keyEsc:!0,overlayClick:!0,closeButton:!0,hideHeader:!1,hideFooter:!1,btn_ok:"OK",btn_cancel:"Cancel",template:'<div class="simple-modal-header">             <h1>{_TITLE_}</h1>           </div>           <div class="simple-modal-body">             <div class="contents">{_CONTENTS_}</div>           </div>           <div class="simple-modal-footer"></div>'},
initialize:function(a){this.setOptions(a)},show:function(a){a||(a={});this._overlay("show");switch(a.model){case "confirm":this.addButton(this.options.btn_ok,"btn primary btn-margin",function(){try{a.callback()}catch(b){}this.hide()});this.addButton(this.options.btn_cancel,"btn secondary");var b=this._drawWindow(a);this._addEscBehaviour();break;case "modal":b=this._drawWindow(a);this._addEscBehaviour();break;case "modal-ajax":b=this._drawWindow(a);this._loadContents({url:a.param.url||"",onRequestComplete:a.param.onRequestComplete||
Function});break;default:this.addButton(this.options.btn_ok,"btn primary"),b=this._drawWindow(a),this._addEscBehaviour()}b.setStyles({width:this.options.width});this.options.hideHeader&&b.addClass("hide-header");this.options.hideFooter&&b.addClass("hide-footer");this.options.closeButton&&this._addCloseButton();if(this.options.draggable){var c=b.getElement(".simple-modal-header");new Drag(b,{handle:c});c.setStyle("cursor","move");b.addClass("draggable")}this._display()},hide:function(){try{"object"==
typeof this.request&&this.request.cancel()}catch(a){}this._overlay("hide")},_drawWindow:function(a){var b=new Element("div#simple-modal",{"class":"simple-modal"});b.inject($$("body")[0]);a=this._template(this.options.template,{_TITLE_:a.title||"Untitled",_CONTENTS_:a.contents||""});b.set("html",a);this._injectAllButtons();this.options.onAppend();return b},addButton:function(a,b,c){a=new Element("a",{title:a,text:a,"class":b,events:{click:(c||this.hide).bind(this)}});this.buttons.push(a);return a},
_injectAllButtons:function(){this.buttons.each(function(a){a.inject($("simple-modal").getElement(".simple-modal-footer"))})},_addCloseButton:function(){var a=new Element("a",{"class":"close",href:"#",html:"x"});a.inject($("simple-modal"),"top");a.addEvent("click",function(a){a&&a.stop();this.hide()}.bind(this));return a},_overlay:function(a){switch(a){case "show":this._overlay("hide");a=new Element("div",{id:"simple-modal-overlay"});a.inject($$("body")[0]);a.setStyle("background-color",this.options.overlayColor);
a.fade("hide").fade(this.options.overlayOpacity);this.options.overlayClick&&a.addEvent("click",function(a){a&&a.stop();this.hide()}.bind(this));this.__resize=this._display.bind(this);window.addEvent("resize",this.__resize);break;case "hide":window.removeEvent("resize",this._display);this.options.keyEsc&&window.removeEvent("ie"!=Browser.name?"keydown":"onkeydown",this._removeSM);try{$("simple-modal-overlay").destroy()}catch(b){}try{$("simple-modal").destroy()}catch(c){}}},_loadContents:function(a){$("simple-modal").addClass("loading");
a.url.match(RegExp(/([^\/\\]+)\.(jpg|png|gif)$/i))?($("simple-modal").addClass("hide-footer"),$("simple-modal-overlay").removeEvents(),new Asset.images([a.url],{onProgress:function(){immagine=this},onComplete:function(){try{$("simple-modal").removeClass("loading");var a=$("simple-modal").getElement(".contents"),c=a.getStyle("padding").split(" "),d=immagine.get("width").toInt()+(c[1].toInt()+c[3].toInt()),e=immagine.get("height").toInt();(new Fx.Tween($("simple-modal"),{duration:"normal",transition:"sine:out",
link:"cancel",property:"width"})).start($("simple-modal").getCoordinates().width,d);(new Fx.Tween(a,{duration:"normal",transition:"sine:out",link:"cancel",property:"height"})).start(a.getCoordinates().height,e).chain(function(){immagine.inject($("simple-modal").getElement(".contents").empty()).fade("hide").fade("in");this._display();this._addEscBehaviour()}.bind(this));(new Fx.Tween($("simple-modal"),{duration:"normal",transition:"sine:out",link:"cancel",property:"left"})).start($("simple-modal").getCoordinates().left,
(window.getCoordinates().width-d)/2)}catch(f){}}.bind(this)})):this.request=(new Request.HTML({evalScripts:!1,url:a.url,method:"get",onRequest:function(){},onSuccess:function(b,c,d,e){$("simple-modal").removeClass("loading");a.onRequestComplete();$("simple-modal").getElement(".contents").set("html",d);eval(e);this._display();this._addEscBehaviour()}.bind(this),onFailure:function(){$("simple-modal").removeClass("loading");$("simple-modal").getElement(".contents").set("html","loading failed")}})).send()},
_display:function(){try{$("simple-modal-overlay").setStyles({height:window.getCoordinates().height})}catch(a){}try{var b=this.options.offsetTop||40;$("simple-modal").setStyles({top:b,left:(window.getCoordinates().width-$("simple-modal").getCoordinates().width)/2})}catch(c){}},_addEscBehaviour:function(){if(this.options.keyEsc)this._removeSM=function(a){"esc"==a.key&&this.hide()}.bind(this),this.options.keyEsc&&window.addEvent("ie"!=Browser.name?"keydown":"onkeydown",this._removeSM)},_template:function(a,
b){for(var c in b)a=a.replace(RegExp("{"+c+"}","g"),b[c]);return a}}),Likes=new Class({Implements:[Options,Events],options:{baseClass:"star",onClass:"star-enabled",type:"trail"},target:null,id:null,initialize:function(a,b){this.target="string"==typeOf(a)?$(a):a;this.id=b;this.attatchListner(this.target)},attatchListner:function(a){a.addEvent("click",function(a){a.preventDefault();this.isLiked()?this.dislike():this.like()}.bind(this))},isLiked:function(){return this.target.hasClass(this.options.onClass)},
like:function(){(new Request.JSON({url:otm.url.rpc,onSuccess:this.likeResult.bind(this),data:{call:this.options.type+".like",id:this.id}})).get()},likeResult:function(a){if(0==a.code)return"notLoggedIn"==a.error?(new SimpleModal({btn_ok:"Alert button"})).show({title:"Inte inloggad",contents:"Du måste logga in för att gilla stigar."}):alert(a.error),!1;var b=this.target.getChildren(".label");this.target.addClass("star-enabled");b.each(function(b){b.set("text",a.likes)})},dislike:function(){(new Request.JSON({url:otm.url.rpc,
onSuccess:this.dislikeResult.bind(this),data:{call:this.options.type+".dislike",id:this.id}})).get()},dislikeResult:function(a){if(0==a.code)return alert(a.error),!1;var b=this.target.getChildren(".label");this.target.removeClass("star-enabled");b.each(function(b){b.set("text",a.likes)})}});void 0==otm&&(otm={});
var MapControl=new Class({Implements:[Options,Events],options:{position:null,css:{},index:-1,controls:[],maximize:{icon:"/images/arrow_expand.png",id:-1,tooltip:"Maximera kartan",action:function(){window.location=otm.url.view.trail+this.options.maximize.id+"&fullscreen=1"}},restore:{icon:"/images/arrow_contract.png",tooltip:"Återställ kartan",id:-1,action:function(){window.location=otm.url.view.trail+this.options.restore.id}},showPanel:{icon:"/images/prospect/otm.panel-expand.png",tooltip:"Display sidebar",
id:-1,action:function(){console.log("show sidebar")}},allTrails:{icon:"/images/add.png",tooltip:"Visa närliggande stigar",visable:!1,id:-1,map:null,icon_add:"/images/add.png",tooltip_add:"Visa närliggande stigar",icon_remove:"/images/remove.png",tooltip_remove:"Göm närliggande stigar",action:function(){(this.visable=!this.visable)?(this.trails?this.trails.setupEvents():this.trails=new Trails(this.map,{color:"#0000ff",colorGraded:!1,markers:!1,zIndex:-1,maxZoom:13,exclude:[parseInt(this.id)]}),$("ctrl_allTrails").set({src:this.icon_remove,
title:this.tooltip_remove}),this.trails.redraw()):($("ctrl_allTrails").set({src:this.icon_add,title:this.tooltip_add}),this.trails.clearEvents(),this.trails.clear())}}},map:null,div:null,initialize:function(a,b){this.setOptions(b);this.map=a;this.options.allTrails.map=a;if(!this.options.position)this.options.position=google.maps.ControlPosition.RIGHT_BOTTOM;this.createHtml();this.options.controls.each(function(a){this.add(a)}.bind(this));this.map.controls[this.options.position].push(this.div)},createHtml:function(){this.div=
new Element("div",{"class":"mapControl"});this.div.index=this.options.index;this.controlUi=new Element("div",{"class":"mapControlUi"});this.controlUi.setStyles(this.options.css);this.div.grab(this.controlUi)},add:function(a){this.options[a]&&this.controlUi.grab(new Element("img",{src:this.options[a].icon,title:this.options[a].tooltip,id:"ctrl_"+a,events:{click:function(){this.options[a].action();this.options[a].toggle&&this.options[a].toggle.action()}.bind(this)}}))}}),Pois=new Class({Implements:[Options,
Events],options:{maxZoom:10,enabled:!0,exclude:[]},map:null,call:"",callback:function(){},markers:[],isRedrawing:!1,initialize:function(a,b){this.map=a;this.setOptions(b);this.setupEvents()},setupEvents:function(){google.maps.event.addListener(this.map,"idle",this.redraw.bind(this))},redraw:function(){this.requestPois()},setupRequest:function(){var a=this.map.getZoom();if(this.options.enabled&&this.options.maxZoom<=a)return this.call="pois.get.marker",this.callback=this.drawMarkers,!0;this.call="";
this.callback=function(){};return!1},requestPois:function(){if(this.setupRequest()){var a=this.map.getBounds();(new Request.JSON({url:"/poi/find.json",onSuccess:this.callback.bind(this),data:{swlat:a.getSouthWest().lat(),swlng:a.getSouthWest().lng(),nelat:a.getNorthEast().lat(),nelng:a.getNorthEast().lng(),zoom:this.map.getZoom()}})).get()}},drawMarkers:function(a){for(var b in this.markers)this.markers[b].unlink=1;var c=a.pois.length;for(b=0;b<c;b++)if(-1==this.options.exclude.indexOf(Number(a.pois[b].id)))this.markers[a.pois[b].id]?
delete this.markers[a.pois[b].id].unlink:(poi=new google.maps.Marker({position:new google.maps.LatLng(a.pois[b].lat,a.pois[b].lng),icon:otm.icons.poi.landmark,map:this.map}),poi.poi=1,poi.id=a.pois[b].id,poi.name=a.pois[b].name,poi.description=a.pois[b].description,this.markers[poi.id]=poi,google.maps.event.addListener(poi,"click",function(){otm.setHistory();window.location=otm.url.view.poi+this.id}),this.fireEvent("onDrawPoi",[poi]));this.markers.each(function(a,b,c){a.unlink&&1==a.unlink&&(this.fireEvent("onUnlinkPoi",
[a]),a.setMap(null),delete c[b])}.bind(this))}});void 0===otm&&(otm={});
var Trails=new Class({Implements:[Options,Events],options:{color:otm.color.trail,colorGraded:!0,zIndex:null,polyline:!0,overlay:"auto",marker:!0,minZoom:10,maxZoom:0,exclude:[]},map:null,call:"",callback:function(){},polylines:[],markers:[],isRedrawing:!1,initialize:function(a,b){this.setOptions(b);this.map=a;this.setupEvents()},redraw:function(){this.requestTrails()},clear:function(){this.polylines.each(function(a,b,c){this.fireEvent("onUnlinkTrail",[a]);a.setMap(null);delete c[b]}.bind(this))},
getTrail:function(a){return this.polylines[a]?this.polylines[a]:this.markers[a]?this.markers[a]:!1},setupEvents:function(){google.maps.event.addListener(this.map,"idle",this.redraw.bind(this))},clearEvents:function(){google.maps.event.clearListeners(this.map,"idle")},setupRequest:function(){var a=this.map.getZoom();if(this.options.markers&&(this.options.minZoom>=a||!this.options.polyline)&&this.options.maxZoom<=a)return this.call="trails.get.marker",this.callback=this.drawMarkers,!0;return this.options.polyline&&
this.options.maxZoom<=a?(this.call="trails.get.polyline",this.callback=this.drawTrails,!0):!1},requestTrails:function(){if(this.setupRequest()){var a=this.map.getBounds();(new Request.JSON({url:"/trail/find.json",onSuccess:this.callback.bind(this),data:{swlat:a.getSouthWest().lat(),swlng:a.getSouthWest().lng(),nelat:a.getNorthEast().lat(),nelng:a.getNorthEast().lng(),zoom:this.map.getZoom()}})).get()}},drawTrails:function(a){for(var b in this.polylines)this.polylines[b].unlink=1;for(b in this.markers)this.markers[b].unlink=
1;Object.each(a.trails,function(b,d){var e;if(-1==this.options.exclude.indexOf(Number(a.trails[d].id)))this.polylines&&this.polylines[a.trails[d].id]?delete this.polylines[a.trails[d].id].unlink:(e=otm.drawTrail(a.trails[d].polyline,{map:this.map,zIndex:this.options.zIndex,color:this.options.colorGraded?otm.color.grade[a.trails[d].grade]:this.options.color}),e.trail=1,e.id=a.trails[d].id,e.name=a.trails[d].name,e.grade=a.trails[d].grade,e.length=a.trails[d].distance,this.polylines[e.id]=e,this.fireEvent("onDrawTrail",
[e]))},this);this.polylines.each(function(a,b,e){a.unlink&&1==a.unlink&&(this.fireEvent("onUnlinkTrail",[a]),a.setMap(null),delete e[b])}.bind(this));this.markers.each(function(a,b,e){a.unlink&&1==a.unlink&&(this.fireEvent("onUnlinkMarker",[a]),a.setMap(null),delete e[b])}.bind(this))},drawMarkers:function(a){if(0!=a.code){for(var b in this.polylines)this.polylines[b].unlink=1;for(b in this.polylines)this.polylines[b].unlink=1;for(b=0;b<a.count;b++){var c;if(-1==this.options.exclude.indexOf(parseInt(a.trails[b].trailId)))this.markers&&
this.markers[a.trails[b].trailId]?delete this.markers[a.trails[b].trailId].unlink:(c=new google.maps.Marker({position:new google.maps.LatLng(a.trails[b].lat,a.trails[b].lng),map:this.map,icon:otm.icons.trail}),c.trail=1,c.trailId=a.trails[b].trailId,c.name=a.trails[b].name,c.grade=a.trails[b].grade,c.length=a.trails[b].distance,this.markers[c.trailId]=c,this.fireEvent("onDrawTrailMarker",[c]))}this.polylines.each(function(a,b,c){this.fireEvent("onUnlinkTrail",[a]);a.setMap(null);delete c[b]}.bind(this));
this.markers.each(function(a,b,c){a.unlink&&1==a.unlink&&(this.fireEvent("onUnlinkMarker",[a]),a.setMap(null),delete c[b])}.bind(this))}}});
